### ISSUE TITLE
Providing readme for each game/module

### ISSUE THREAD

**Issue by ZeekHuge** [AnirbanBanik1998/Modern_Speak_and_Spell#1]
Its a cool project, but has many submodules/games etc which need to be started manually.This makes documentation and instructions pretty crucial for the project.

I see there are files like [launcher.md](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/Game/Game_launcher/launcher.md) and [instructions.md](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/Game/Games/Hangman/instructions.md), but it would probably be better to simply name them `Readme.md` as it will make github show the file by default in the module directory (plus, its a standard and developers' eyes are good at finding `Readme.md` by default instead of `<something-else>.md`)

**Comment by AnirbanBanik1998** [comment]
Thanks ZeekHuge for your suggestion! I have renamed my documentation files to README.md. Those who prefer documentation in markdown format can view them but for detailed descriptions, they have to visit the documentation hosted on Github page.

**Comment by AnirbanBanik1998** [comment]
Closing this issue.
