### ISSUE TITLE
`sudo` in `setup.sh`

### ISSUE THREAD

**Issue by ZeekHuge** [AnirbanBanik1998/Modern_Speak_and_Spell#2]
Its never a good idea to use `sudo` inside a script (specially when something is intended for regular users). So I would suggest following for the [`setup.sh`](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/setup.sh)
 - Do not use `sudo` inside the script. Instead, check if script is being run as sudo using something like
```
if [ "$EUID" -ne 0 ]; then
    echo "Requires root to install dependencies. Use : sudo setup.sh"
    exit 1
fi
```
when the script starts.

- Instead of using `apt-get install <package>`, use `apt-get install -y <package>`. The former runs interactively (asks for `yes/no`) while the latter does not.

**Comment by AnirbanBanik1998** [comment]
Thanks ZeekHuge for your suggestion, I have updated my setup.sh file accordingly.

**Comment by ZeekHuge** [comment]
You probably missed [this line](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/setup.sh#L29). It looks cool otherwise. This issue can be closed now.

Thanks,

**Comment by AnirbanBanik1998** [comment]
Updated the script...Thanks...closing the issue.
