### ISSUE TITLE
Confusion in the `Recorder` class

### ISSUE THREAD

**Issue by ZeekHuge** [AnirbanBanik1998/Modern_Speak_and_Spell#3]
The [`Recorder`](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/API/recorder.py#L12) class in the API has 2 different `self.start` being used.

The [1st one is a method](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/API/recorder.py#L61) while the [other one is a variable](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/API/recorder.py#L89). 

This will basically result in hiding one of them by other, based on which statement gets executed later.
Also, this creates confusion while understanding what you really are trying to do there. Also, is the [`self.start` variable](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/API/recorder.py#L89) really needed to be in the `self` object ? ? Looks like its local to the [`record()`](https://github.com/AnirbanBanik1998/Modern_Speak_and_Spell/blob/master/API/recorder.py#L81) hence, you might just be able to use a local variable.
But, cant be sure as the code is a bit confusing as of now.

**Comment by AnirbanBanik1998** [comment]
Yeah you're right...I modified my code...renaming some variables which can be kept local...didn't notice it earlier...Thanks for your suggestion

**Comment by AnirbanBanik1998** [comment]
I guess this issue is also resolved...so closing it.
